//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adrese
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adrese()
        {
            this.Angajati = new HashSet<Angajati>();
        }
    
        public int Id_Adresa { get; set; }
        public string Strada { get; set; }
        public int Nr_Strada { get; set; }
        public string Bloc { get; set; }
        public Nullable<int> Apartament { get; set; }
        public string Oras { get; set; }
        public string Judet_Sector { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Angajati> Angajati { get; set; }
    }
}
