//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Angajati
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Angajati()
        {
            this.Angajati_Departament = new HashSet<Angajati_Departament>();
        }
    
        public int Id_Angajat { get; set; }
        public Nullable<int> Id_Grad { get; set; }
        public string Nume_Angajat { get; set; }
        public string Prenume_Angajat { get; set; }
        public string CNP { get; set; }
        public string Numar_Telefon { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Data_Nastere { get; set; }
        public System.DateTime Data_Angajare { get; set; }
        public Nullable<System.DateTime> Data_Plecare { get; set; }
        public string Observatii { get; set; }
        public Nullable<int> Id_Adresa { get; set; }
        public Nullable<int> Id_Salariu { get; set; }
        public Nullable<int> Id_Functie { get; set; }
        public Nullable<int> Id_Departament { get; set; }
        public Nullable<int> Id_Proiect_Curent { get; set; }
        public Nullable<int> Id_Tabel_Rude { get; set; }
        public Nullable<int> Id_Fisa_Med { get; set; }
    
        public virtual Adrese Adrese { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Angajati_Departament> Angajati_Departament { get; set; }
        public virtual Departamente Departamente { get; set; }
        public virtual Fise_Medicale Fise_Medicale { get; set; }
        public virtual Functii Functii { get; set; }
        public virtual Grade Grade { get; set; }
        public virtual Proiecte Proiecte { get; set; }
        public virtual Salarii Salarii { get; set; }
        public virtual Tabel_Rude Tabel_Rude { get; set; }
    }
}
