//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Angajati_Departament
    {
        public int Id_Angajat { get; set; }
        public int Id_Departament { get; set; }
        public System.DateTime Data_Inceput { get; set; }
        public Nullable<System.DateTime> Data_Sfarsit { get; set; }
    
        public virtual Angajati Angajati { get; set; }
        public virtual Departamente Departamente { get; set; }
    }
}
