//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HREntities1 : DbContext
    {
        public HREntities1()
            : base("name=HREntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adrese> Adrese { get; set; }
        public virtual DbSet<Angajati> Angajati { get; set; }
        public virtual DbSet<Departamente> Departamente { get; set; }
        public virtual DbSet<Fise_Medicale> Fise_Medicale { get; set; }
        public virtual DbSet<Functii> Functii { get; set; }
        public virtual DbSet<Grade> Grade { get; set; }
        public virtual DbSet<Proiecte> Proiecte { get; set; }
        public virtual DbSet<Salarii> Salarii { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Angajati_Departament> Angajati_Departament { get; set; }
        public virtual DbSet<Rude> Rude { get; set; }
    
        public virtual int MoveAngajat(string numeAngajat, string prenumeAngajat, string noulDepartament, string nouaFunctie)
        {
            var numeAngajatParameter = numeAngajat != null ?
                new ObjectParameter("NumeAngajat", numeAngajat) :
                new ObjectParameter("NumeAngajat", typeof(string));
    
            var prenumeAngajatParameter = prenumeAngajat != null ?
                new ObjectParameter("PrenumeAngajat", prenumeAngajat) :
                new ObjectParameter("PrenumeAngajat", typeof(string));
    
            var noulDepartamentParameter = noulDepartament != null ?
                new ObjectParameter("NoulDepartament", noulDepartament) :
                new ObjectParameter("NoulDepartament", typeof(string));
    
            var nouaFunctieParameter = nouaFunctie != null ?
                new ObjectParameter("NouaFunctie", nouaFunctie) :
                new ObjectParameter("NouaFunctie", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MoveAngajat", numeAngajatParameter, prenumeAngajatParameter, noulDepartamentParameter, nouaFunctieParameter);
        }
    
        public virtual int MoveDepartament(string numeAngajat, string prenumeAngajat, string noulDepartament)
        {
            var numeAngajatParameter = numeAngajat != null ?
                new ObjectParameter("NumeAngajat", numeAngajat) :
                new ObjectParameter("NumeAngajat", typeof(string));
    
            var prenumeAngajatParameter = prenumeAngajat != null ?
                new ObjectParameter("PrenumeAngajat", prenumeAngajat) :
                new ObjectParameter("PrenumeAngajat", typeof(string));
    
            var noulDepartamentParameter = noulDepartament != null ?
                new ObjectParameter("NoulDepartament", noulDepartament) :
                new ObjectParameter("NoulDepartament", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MoveDepartament", numeAngajatParameter, prenumeAngajatParameter, noulDepartamentParameter);
        }
    
        public virtual int MoveFunctie(string numeAngajat, string prenumeAngajat, string nouaFunctie)
        {
            var numeAngajatParameter = numeAngajat != null ?
                new ObjectParameter("NumeAngajat", numeAngajat) :
                new ObjectParameter("NumeAngajat", typeof(string));
    
            var prenumeAngajatParameter = prenumeAngajat != null ?
                new ObjectParameter("PrenumeAngajat", prenumeAngajat) :
                new ObjectParameter("PrenumeAngajat", typeof(string));
    
            var nouaFunctieParameter = nouaFunctie != null ?
                new ObjectParameter("NouaFunctie", nouaFunctie) :
                new ObjectParameter("NouaFunctie", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MoveFunctie", numeAngajatParameter, prenumeAngajatParameter, nouaFunctieParameter);
        }
    
        public virtual int ModifyDepartamente(string numeDepartament, string numeNou, string numeSef)
        {
            var numeDepartamentParameter = numeDepartament != null ?
                new ObjectParameter("NumeDepartament", numeDepartament) :
                new ObjectParameter("NumeDepartament", typeof(string));
    
            var numeNouParameter = numeNou != null ?
                new ObjectParameter("NumeNou", numeNou) :
                new ObjectParameter("NumeNou", typeof(string));
    
            var numeSefParameter = numeSef != null ?
                new ObjectParameter("NumeSef", numeSef) :
                new ObjectParameter("NumeSef", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ModifyDepartamente", numeDepartamentParameter, numeNouParameter, numeSefParameter);
        }
    }
}
