//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HREntities1 : DbContext
    {
        public HREntities1()
            : base("name=HREntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adrese> Adrese { get; set; }
        public virtual DbSet<Angajati> Angajati { get; set; }
        public virtual DbSet<Departamente> Departamente { get; set; }
        public virtual DbSet<Fise_Medicale> Fise_Medicale { get; set; }
        public virtual DbSet<Functii> Functii { get; set; }
        public virtual DbSet<Grade> Grade { get; set; }
        public virtual DbSet<Proiecte> Proiecte { get; set; }
        public virtual DbSet<Salarii> Salarii { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Angajati_Departament> Angajati_Departament { get; set; }
        public virtual DbSet<Rude> Rude { get; set; }
    }
}
