//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vechime_Angajati
    {
        public int Id_Angajat { get; set; }
        public Nullable<int> Id_Functie { get; set; }
        public Nullable<int> Id_Grad { get; set; }
        public string Nume_Angajat { get; set; }
        public string Prenume_Angajat { get; set; }
        public Nullable<int> Vechime { get; set; }
    }
}
